#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Apr  6 02:06:18 2023

@author: wyk
"""

import numpy as np
import matplotlib.pyplot as plt
import os

obj_file = open('modelnet40_normal_resampled_original/modelnet40_shape_names.txt')
obj_list = obj_file.read()
obj_list = obj_list.split('\n')[:-1]



for obj in obj_list:
    

    directory = 'modelnet40_normal_resampled_original/'+'/'+obj #where the original files are

    for filename in os.listdir(directory): # list all files in directory

        my_file = open(directory+'/'+filename,'r') 
    
        data = my_file.read()
        data = list(data.split("\n"))
        data = [item.split(',') for item in data]
        data = data[:-1]
        x_list=[]
        y_list=[]
        z_list=[]
        for i in range (len(data)):
            x = float(data[i][0])
            x_list.append(x)
            
            y = float(data[i][1])
            y_list.append(y)
            
            z = float(data[i][2])
            z_list.append(z)
            
            # xyz = np.column_stack((x_list,y_list,z_list))
            # xyz=xyz.tolist()

        x0 = sum(x_list)/len(x_list)
        y0 = sum(y_list)/len(y_list)
        z0 = sum(z_list)/len(z_list)
            
        # # xyz0=np.column_stack((x0,y0,z0))

        # file = open('modelnet40_0228/airplane/airplane_0001.txt','w')
        file = open('modelnet40_0228/three quarters/'+obj+'/'+filename,'w') 

        for i in range(len(data)-1):
            
            # delete 1/2 point cloud, the one smaller than x0 
            if float(data[i][0]) > x0 and float(data[i][2]) > z0: # if x is > x0
            
                file.writelines(data[i][0]+","+data[i][1]+","+data[i][2]+","+data[i][3]+","+ data[i][4]+","+data[i][5])
                file.write("\n")
        
        file.close()
            
        newfile = open('modelnet40_0228/three quarters/'+obj+'/'+filename,'r')
    
        lines = newfile.read()
        colist = lines.split("\n")    
    
        for i in range(len(colist)-1):
            
            item = colist[i].split(',')   
            if len(item) != 6:
                print(i ,item)
            
            